services:
  - type: web
    name: mhcqms-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
    healthCheckPath: /health

  - type: web
    name: mhcqms-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: .
    envVars:
      - key: REACT_APP_API_URL
        value: https://mhcqms.onrender.com/api
