@echo off
echo Starting Healthcare Queue Management System Backend...
echo.
cd backend
echo Installing Python dependencies...
pip install -r requirements.txt
echo.
echo Initializing database...
python init_db.py
echo.
echo Starting FastAPI server...
python main.py
pause
